fix: 1 commit only

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -64,19 +64,18 @@ jobs:
 
     - name: Check commit message format
       run: |
+        if [ "${{ github.event_name }}" == "push" ]; then
         COMMIT_MESSAGE=$(git log --format="%s" -n 1 ${{ github.sha }})
         PATTERN="^(feat:|fix:|docs:|style:|refactor:|test:|[A-Z][a-z]*:)"
-        IFS=$'\n' # Configura el separador interno para manejar espacios en mensajes
-
-        for COMMIT_MESSAGE in "${COMMIT_MESSAGES}"; do
-          if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
-            if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
-              echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
-              exit 1
-            else
-              echo "Commit message '$COMMIT_MESSAGE' follows the format."
-            fi
-          else
-            echo "Skipping commit message verification for pull request merge commit."
+        
+        if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
+          if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
+            echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
+            exit 1
           fi
-        done
+        else
+          echo "Skipping commit message verification for pull request merge commit."
+        fi
+        else
+          echo "Skipping commit message verification for pull request."
+        fi
