fix: merge pull request exception

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -63,8 +63,22 @@ jobs:
 
     - name: Check commit message format
       run: |
-        commit_message=$(git log --format=%s -n 1 ${{github.sha}})
-        if ! echo "$commit_message" | grep -E '^(feat:|fix:|docs:|style:|refactor:|test:|[A-Z][a-z]*:)' >/dev/null; then
-          echo "Error: Commit message does not match the expected format: $commit_message"
-          exit 1
+        if [ "${{ github.event_name }}" == "push" ]; then
+          COMMIT_MESSAGES=$(git log --format="%s" ${GITHUB_SHA}^1..${GITHUB_SHA})
+          PATTERN="^(feat:|fix:|docs:|style:|refactor:|test:|[A-Z][a-z]*:)"
+
+          for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
+            # Excluir mensajes de pull request generados automáticamente
+            if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
+              if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
+                echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
+                exit 1
+              fi
+            else
+              echo "Skipping commit message verification for pull request merge commit."
+            fi
+          done
+        else
+          echo "Skipping commit message verification for pull request."
         fi
+
