fix: merge pull request exception 9

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -64,24 +64,18 @@ jobs:
     - name: Check commit message format
       run: |
         if [ "${{ github.event_name }}" == "push" ]; then
-          # Obtener el commit anterior al último push, o si es el primer commit, obtener el propio commit
-          BASE_COMMIT=$(git rev-parse HEAD^1 2>/dev/null || git rev-parse HEAD)
-
-          COMMIT_MESSAGES=$(git log --format="%s" $BASE_COMMIT..${{ github.sha }})
+          COMMIT_MESSAGE=$(git log --format="%s" -n 1 ${{ github.sha }})
           PATTERN="^(feat:|fix:|docs:|style:|refactor:|test:|[A-Z][a-z]*:)"
           
-          for COMMIT_MESSAGE in $COMMIT_MESSAGES; do
-            if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
-              if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
-                echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
-                exit 1
-              fi
-            else
-              echo "Skipping commit message verification for pull request merge commit."
+          if [[ ! "$COMMIT_MESSAGE" =~ "Merge pull request" ]]; then
+            if [[ ! "$COMMIT_MESSAGE" =~ $PATTERN ]]; then
+              echo "Error: El mensaje de commit '$COMMIT_MESSAGE' no sigue el formato esperado."
+              exit 1
             fi
-          done
+          else
+            echo "Skipping commit message verification for pull request merge commit."
+          fi
         else
           echo "Skipping commit message verification for pull request."
         fi
-
 
